import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts", "src/internal.ts"],
  format: ["esm"],
  platform: "node",
  target: "node24",
  outDir: "dist",
  clean: true,
  sourcemap: true,
  splitting: true,
  banner: {
    js: "#!/usr/bin/env node",
  },
  define: {
    __DREAMBOARD_BUILD_CHANNEL__: JSON.stringify(
      process.env.DREAMBOARD_BUILD_CHANNEL ?? "development",
    ),
  },
  noExternal: [
    "@dreamboard-games/api-client",
    "@dreamboard-games/gameplay-authority-client",
    "citty",
    "clsx",
    "consola",
    "lucide-react",
    "picocolors",
    "postcss",
    "sonner",
    "tailwind-merge",
    "tw-animate-css",
    "zod",
    "zustand",
  ],
  external: [
    "@dreamboard-games/sdk",
    "@dreamboard-games/ui-host-runtime",
    "@napi-rs/keyring",
    "esbuild",
    "playwright",
    "playwright-core",
    "chromium-bidi",
    "electron",
    "react",
    "react-dom",
    "tailwindcss",
    "vaul",
    "vite",
  ],
});
