import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { AUTHORING_RELEASE_SET } from "../../release/authoring-release-set.js";
import { REDUCER_TESTING_TYPES_WRAPPER_CONTENT } from "../../templates/testing-types-content.js";
import {
  MANIFEST_TYPECHECK_CONFIG_FILE,
  PROJECT_CONFIG_FILE,
  PROJECT_DIR_NAME,
} from "../../constants.js";
import type { LocalMaintainerRegistryConfig } from "../../types.js";
import { ensureDir } from "../../utils/fs.js";
import { materializeManifest } from "./manifest-authoring.js";
import { isDynamicSeedPath } from "./scaffold-ownership.js";
import {
  normalizeOwnedProjectPath,
  readWorkspaceTextFile,
  readWorkspaceTextFileIfExists,
  removeWorkspacePath,
  resolveWorkspacePath,
  workspacePathExists,
  writeWorkspaceTextFile,
} from "./workspace-path.js";
import {
  FRAMEWORK_PNPM_OVERRIDES,
  FRAMEWORK_REACT_DEPENDENCIES,
  FRAMEWORK_ZOD_VERSION,
} from "./framework-dependencies.js";

type StaticScaffoldMode = "new" | "update";
type StaticAssetEntry = {
  targetPath: string;
  content: string;
};
type StaticScaffoldOptions = {
  localMaintainerRegistry?: LocalMaintainerRegistryConfig | null;
};
type RootPackageJsonShape = {
  private?: boolean;
  packageManager?: string;
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  overrides?: Record<string, unknown>;
  pnpm?: Record<string, unknown>;
  [key: string]: unknown;
};

const DREAMBOARD_SCAFFOLD_REFRESH_COMMAND =
  "dreamboard project create or dreamboard project clone";
const DREAMBOARD_GITIGNORE_BLOCK = [
  "# Dreamboard local state",
  ".dreamboard/state.json",
  ".dreamboard/snapshot.json",
  ".dreamboard/dev/",
  ".dreamboard/generated/",
  "node_modules/",
  "ui/node_modules/",
  "",
].join("\n");
const TESTING_TYPES_STUB =
  "export function defineScenario(scenario) { return scenario; }\n";
const GENERATED_TESTING_TYPES_PREFIX = "// Generated by dreamboard";
const GENERATED_SCENARIO_PREFIX = "// Generated by dreamboard scaffold.";
function buildInitialScenarioContent(players: number): string {
  return `${GENERATED_SCENARIO_PREFIX}
import { defineScenario } from "../testing-types";

export default defineScenario({
  id: "smoke-initial-turn",
  description:
    "Sanity check that the scaffolded workspace boots into its initial phase.",
  setup: { players: ${players}, seed: 1337 },
  given: [],
  when: [],
  then: ({ expect, state }) => {
    expect(state()).toBeDefined();
  },
});
`;
}
const STATIC_ASSET_ROOT = resolveStaticAssetRoot();
const SDK_DEPENDENCY_RANGES = {
  "@dreamboard-games/sdk": AUTHORING_RELEASE_SET.packages.sdk.version,
} as const;
const DEV_HOST_DEPENDENCY_RANGES = {
  "@dreamboard-games/dev-host": AUTHORING_RELEASE_SET.packages.devHost.version,
} as const;

const FRAMEWORK_SCRIPTS = {
  dev: "dreamboard dev",
  "test:ui":
    "tsx --tsconfig test/tsconfig.tsx-runtime.json --test test/ui/**/*.test.tsx",
  typecheck: `tsc --noEmit -p ${MANIFEST_TYPECHECK_CONFIG_FILE} && tsc --noEmit -p app/tsconfig.json && tsc --noEmit -p ui/tsconfig.json`,
  "typecheck:manifest": `tsc --noEmit -p ${MANIFEST_TYPECHECK_CONFIG_FILE}`,
  "typecheck:app": "tsc --noEmit -p app/tsconfig.json",
  "typecheck:ui": "tsc --noEmit -p ui/tsconfig.json",
} as const;
const SHARED_DEPENDENCIES = {
  ...FRAMEWORK_REACT_DEPENDENCIES,
} as const;
const ROOT_APP_DEPENDENCIES = {
  zod: FRAMEWORK_ZOD_VERSION,
} as const;
const SHARED_DEV_DEPENDENCIES = {
  typescript: "^5.9.2",
  "@types/node": "^24.5.2",
  "@types/react": "^19.0.0",
  "@types/react-dom": "^19.0.0",
  csstype: "^3.1.3",
  tsx: "^4.20.5",
} as const;

export async function scaffoldStaticWorkspace(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions = {},
): Promise<void> {
  await writeFrameworkStaticFiles(projectRoot, mode, options);
  await ensureDreamboardGitignore(projectRoot);
  await writeManifestTypecheckTsconfig(projectRoot);

  await ensureDir(resolveWorkspacePath(projectRoot, "test/scenarios"));

  await writeTestReadme(projectRoot);
  const initialTestPlayerCount = await inferInitialTestPlayerCount(projectRoot);
  await writeInitialScenario(projectRoot, mode, initialTestPlayerCount);
  await writeTestingTypes(projectRoot, mode);
  await writeTestTsconfig(projectRoot);
}

async function ensureDreamboardGitignore(projectRoot: string): Promise<void> {
  const existing = await readWorkspaceTextFileIfExists(
    projectRoot,
    ".gitignore",
  );
  if (existing?.includes(".dreamboard/state.json")) {
    return;
  }
  await writeWorkspaceTextFile(
    projectRoot,
    ".gitignore",
    `${existing ? `${existing.trimEnd()}\n\n` : ""}${DREAMBOARD_GITIGNORE_BLOCK}`,
  );
}

export async function assertCliStaticScaffoldComplete(
  projectRoot: string,
  deletedPaths: readonly string[] = [],
): Promise<void> {
  const expectedEntries = await getExpectedStaticEntries(projectRoot);
  const missingOrBlankPaths: string[] = [];

  for (const entry of expectedEntries) {
    const content = await readWorkspaceTextFileIfExists(
      projectRoot,
      entry.targetPath,
    );

    if (content === null || content.trim().length === 0) {
      missingOrBlankPaths.push(entry.targetPath);
    }
  }

  const staticPaths = new Set(expectedEntries.map((entry) => entry.targetPath));
  const deletedStaticPaths = deletedPaths
    .map(normalizeOwnedProjectPath)
    .filter(
      (filePath): filePath is string =>
        filePath !== null && staticPaths.has(filePath),
    )
    .sort();

  if (missingOrBlankPaths.length === 0 && deletedStaticPaths.length === 0) {
    return;
  }

  const problems: string[] = [];
  if (missingOrBlankPaths.length > 0) {
    problems.push(
      `missing or blank: ${summarizePaths(missingOrBlankPaths.sort())}`,
    );
  }
  if (deletedStaticPaths.length > 0) {
    problems.push(`deleted: ${summarizePaths(deletedStaticPaths)}`);
  }

  throw new Error(
    `CLI static scaffold is incomplete (${problems.join("; ")}). Refresh the project scaffold with ${DREAMBOARD_SCAFFOLD_REFRESH_COMMAND} before building or testing.`,
  );
}

async function writeFrameworkStaticFiles(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions,
): Promise<void> {
  const assetEntries = await getStaticAssetEntries();

  for (const entry of assetEntries) {
    // Dynamic seed files are user-customizable: only write them on first
    // scaffold; preserve existing content on subsequent updates.
    if (mode === "update" && isDynamicSeedPath(entry.targetPath)) {
      const existing = await readWorkspaceTextFileIfExists(
        projectRoot,
        entry.targetPath,
      );
      if (existing !== null && existing.trim().length > 0) {
        continue;
      }
    }
    await writeWorkspaceTextFile(projectRoot, entry.targetPath, entry.content);
  }

  for (const entry of await getDynamicStaticEntries(
    projectRoot,
    mode,
    options,
  )) {
    await writeWorkspaceTextFile(projectRoot, entry.targetPath, entry.content);
  }

  if (!options.localMaintainerRegistry) {
    await removeWorkspacePath(projectRoot, ".npmrc", { force: true });
  }
}

async function writeTestReadme(projectRoot: string): Promise<void> {
  await writeWorkspaceTextFile(
    projectRoot,
    "test/README.md",
    "# Dreamboard Test Workspace\n\nSelf-contained TypeScript scenarios live in `test/scenarios/*.scenario.ts`.\n\n1. Define normal setup with `setup: { players, seed, setupProfileId? }`.\n2. Establish the state under test with typed commands in `given`.\n3. Put the behavior being proved in typed commands in `when`.\n4. Observe state and player views, or run clone-only rejection probes, in `then`.\n5. Run deterministic scenarios with `dreamboard test`; select one with `dreamboard test --scenario <scenario-id>`.\n\nImport `defineScenario` from `../testing-types`.\n",
  );
}

async function writeInitialScenario(
  projectRoot: string,
  mode: StaticScaffoldMode,
  players: number,
): Promise<void> {
  const content = buildInitialScenarioContent(players);
  if (mode === "new") {
    await writeWorkspaceTextFile(
      projectRoot,
      "test/scenarios/smoke-initial-turn.scenario.ts",
      content,
    );
    return;
  }

  const existing = await readWorkspaceTextFileIfExists(
    projectRoot,
    "test/scenarios/smoke-initial-turn.scenario.ts",
  );
  if (
    existing === null ||
    existing.trim().length === 0 ||
    existing.startsWith(GENERATED_SCENARIO_PREFIX)
  ) {
    await writeWorkspaceTextFile(
      projectRoot,
      "test/scenarios/smoke-initial-turn.scenario.ts",
      content,
    );
  }
}

async function writeTestingTypes(
  projectRoot: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  if (mode === "new") {
    await writeWorkspaceTextFile(
      projectRoot,
      "test/testing-types.ts",
      REDUCER_TESTING_TYPES_WRAPPER_CONTENT,
    );
    return;
  }

  const existing = await readWorkspaceTextFileIfExists(
    projectRoot,
    "test/testing-types.ts",
  );
  if (shouldRefreshGeneratedTestingTypes(existing)) {
    await writeWorkspaceTextFile(
      projectRoot,
      "test/testing-types.ts",
      REDUCER_TESTING_TYPES_WRAPPER_CONTENT,
    );
  }
}

async function writeTestTsconfig(projectRoot: string): Promise<void> {
  await writeWorkspaceTextFile(
    projectRoot,
    "test/tsconfig.json",
    `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: [
          "./**/*.ts",
          "./**/*.d.ts",
          "../shared/**/*.ts",
          "../shared/**/*.d.ts",
        ],
      },
      null,
      2,
    )}\n`,
  );
}

async function writeManifestTypecheckTsconfig(
  projectRoot: string,
): Promise<void> {
  await writeWorkspaceTextFile(
    projectRoot,
    MANIFEST_TYPECHECK_CONFIG_FILE,
    `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
          allowImportingTsExtensions: true,
        },
        include: ["./manifest.ts"],
      },
      null,
      2,
    )}\n`,
  );
}

function shouldRefreshGeneratedTestingTypes(
  existingContent: string | null,
): boolean {
  if (existingContent === null || existingContent.trim().length === 0) {
    return true;
  }
  if (existingContent === TESTING_TYPES_STUB) {
    return true;
  }
  return existingContent.startsWith(GENERATED_TESTING_TYPES_PREFIX);
}

async function inferInitialTestPlayerCount(
  projectRoot: string,
): Promise<number> {
  if (!(await workspacePathExists(projectRoot, "manifest.ts"))) {
    return 4;
  }

  try {
    const manifest = await materializeManifest(projectRoot);
    return manifest.players.optimalPlayers ?? manifest.players.minPlayers ?? 4;
  } catch {
    return 4;
  }
}

export function resolveStaticAssetRoot(
  importUrl: string = import.meta.url,
): string {
  const candidates = [
    fileURLToPath(new URL("../../scaffold/assets/static/", importUrl)),
    fileURLToPath(new URL("./scaffold/assets/static/", importUrl)),
    fileURLToPath(new URL("../scaffold/assets/static/", importUrl)),
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  throw new Error(
    `Unable to locate CLI static scaffold assets. Checked: ${candidates.join(", ")}`,
  );
}

async function getStaticAssetEntries(): Promise<StaticAssetEntry[]> {
  const files = await walkFiles(STATIC_ASSET_ROOT);
  const entries: StaticAssetEntry[] = [];

  for (const filePath of files) {
    const targetPath = normalizeOwnedProjectPath(
      path.relative(STATIC_ASSET_ROOT, filePath).replaceAll(path.sep, "/"),
    );
    if (targetPath === null) {
      throw new Error(`Unsafe static scaffold asset path: ${filePath}`);
    }
    entries.push({
      targetPath,
      content: await readFile(filePath, "utf8"),
    });
  }

  entries.sort((left, right) =>
    left.targetPath.localeCompare(right.targetPath),
  );
  return entries;
}

async function getDynamicStaticEntries(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions = {},
): Promise<StaticAssetEntry[]> {
  const entries: StaticAssetEntry[] = [
    {
      targetPath: "package.json",
      content: await buildRootPackageJson(projectRoot, mode, options),
    },
    {
      targetPath: "ui/package.json",
      content: buildUiPackageJson(),
    },
  ];

  if (options.localMaintainerRegistry) {
    entries.push({
      targetPath: ".npmrc",
      content: buildWorkspaceNpmrc(options.localMaintainerRegistry.registryUrl),
    });
  }

  return entries;
}

async function getExpectedStaticEntries(
  projectRoot: string,
): Promise<StaticAssetEntry[]> {
  const entries = [
    ...(await getStaticAssetEntries()).filter(
      (entry) => entry.targetPath !== ".npmrc",
    ),
    ...(await getDynamicStaticEntries(projectRoot, "update")),
  ];
  entries.sort((left, right) =>
    left.targetPath.localeCompare(right.targetPath),
  );
  return entries;
}

async function walkFiles(rootDir: string): Promise<string[]> {
  const files: string[] = [];
  const stack = [rootDir];

  while (stack.length > 0) {
    const currentDir = stack.pop();
    if (!currentDir) continue;

    const entries = await readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile()) {
        files.push(fullPath);
      }
    }
  }

  files.sort((left, right) => left.localeCompare(right));
  return files;
}

async function buildRootPackageJson(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions,
): Promise<string> {
  const dreamboardPackageRanges = resolveDreamboardPackageRanges(options);
  const existingPackageJson =
    mode === "update" &&
    (await workspacePathExists(projectRoot, "package.json"))
      ? (JSON.parse(
          await readWorkspaceTextFile(projectRoot, "package.json"),
        ) as RootPackageJsonShape)
      : null;
  const frameworkDependencies = {
    "@dreamboard-games/sdk": dreamboardPackageRanges["@dreamboard-games/sdk"],
    ...SHARED_DEPENDENCIES,
    ...ROOT_APP_DEPENDENCIES,
  };
  const frameworkDevDependencies = {
    ...SHARED_DEV_DEPENDENCIES,
    ...DEV_HOST_DEPENDENCY_RANGES,
  };
  const nextPackageJson: RootPackageJsonShape = {
    ...(existingPackageJson ?? {}),
    private: true,
    packageManager: AUTHORING_RELEASE_SET.packageManager,
    scripts: {
      ...(existingPackageJson?.scripts ?? {}),
      ...FRAMEWORK_SCRIPTS,
    },
    dependencies: {
      ...(existingPackageJson?.dependencies ?? {}),
      ...frameworkDependencies,
    },
    devDependencies: {
      ...(existingPackageJson?.devDependencies ?? {}),
      ...frameworkDevDependencies,
    },
    pnpm: mergePnpmConfig(existingPackageJson?.pnpm, dreamboardPackageRanges),
  };
  return `${JSON.stringify(nextPackageJson, null, 2)}\n`;
}

function resolveDreamboardPackageRanges(
  options: StaticScaffoldOptions,
): Record<
  | "@dreamboard-games/api-client"
  | "@dreamboard-games/dev-host"
  | "@dreamboard-games/sdk",
  string
> {
  return {
    "@dreamboard-games/api-client":
      options.localMaintainerRegistry?.packages[
        "@dreamboard-games/api-client"
      ] ?? AUTHORING_RELEASE_SET.packages.apiClient.version,
    "@dreamboard-games/dev-host":
      AUTHORING_RELEASE_SET.packages.devHost.version,
    "@dreamboard-games/sdk":
      options.localMaintainerRegistry?.packages["@dreamboard-games/sdk"] ??
      SDK_DEPENDENCY_RANGES["@dreamboard-games/sdk"],
  };
}

function mergePnpmConfig(
  existingPnpm: Record<string, unknown> | undefined,
  dreamboardPackageRanges: Record<string, string>,
): Record<string, unknown> {
  const existingOverrides =
    existingPnpm?.overrides &&
    typeof existingPnpm.overrides === "object" &&
    !Array.isArray(existingPnpm.overrides)
      ? (existingPnpm.overrides as Record<string, unknown>)
      : {};
  return {
    ...(existingPnpm ?? {}),
    overrides: {
      ...existingOverrides,
      ...FRAMEWORK_PNPM_OVERRIDES,
      ...dreamboardPackageRanges,
    },
  };
}

function buildWorkspaceNpmrc(registryUrl: string): string {
  return `@dreamboard-games:registry=${registryUrl}\n`;
}

function buildUiPackageJson(): string {
  return `${JSON.stringify(
    {
      private: true,
      dependencies: SHARED_DEPENDENCIES,
      devDependencies: SHARED_DEV_DEPENDENCIES,
    },
    null,
    2,
  )}\n`;
}

function summarizePaths(paths: readonly string[]): string {
  const maxShown = 5;
  const shown = paths.slice(0, maxShown).join(", ");
  if (paths.length <= maxShown) return shown;
  return `${shown}, and ${paths.length - maxShown} more`;
}
