// Generated by scripts/generate-authoring-release-set.ts. Do not edit by hand.
import type { AuthoringReleaseSetV1 } from "./authoring-release-set.js";

export const AUTHORING_RELEASE_SET = {
  "schemaVersion": 1,
  "channel": "public",
  "packages": {
    "cli": {
      "name": "@dreamboard-games/cli",
      "version": "0.1.30-alpha.46"
    },
    "sdk": {
      "name": "@dreamboard-games/sdk",
      "version": "0.4.0-alpha.10"
    },
    "apiClient": {
      "name": "@dreamboard-games/api-client",
      "version": "0.3.0-alpha.4"
    },
    "devHost": {
      "name": "@dreamboard-games/dev-host",
      "version": "0.1.30-alpha.29"
    }
  },
  "protocols": {
    "authoringAdapter": 1,
    "devHost": 1,
    "verifier": 1
  },
  "schemas": {
    "scaffold": 2,
    "manifest": 2,
    "generatedArtifacts": 1
  },
  "registry": {
    "kind": "public-npm",
    "portable": true
  },
  "packageManager": "pnpm@10.4.1",
  "releaseSetId": "sha256:b2e670e9c937f22836f194a96387f2a26f18b346cb83608cbe09bd60d6314ce6"
} as const satisfies AuthoringReleaseSetV1;
