// Generated by scripts/generate-authoring-release-set.ts. Do not edit by hand.
import type { AuthoringReleaseSetV1 } from "./authoring-release-set.js";

export const AUTHORING_RELEASE_SET = {
  "schemaVersion": 1,
  "channel": "public",
  "packages": {
    "cli": {
      "name": "@dreamboard-games/cli",
      "version": "0.1.30-alpha.43"
    },
    "sdk": {
      "name": "@dreamboard-games/sdk",
      "version": "0.4.0-alpha.8"
    },
    "apiClient": {
      "name": "@dreamboard-games/api-client",
      "version": "0.3.0-alpha.4"
    },
    "devHost": {
      "name": "@dreamboard-games/dev-host",
      "version": "0.1.30-alpha.27"
    }
  },
  "protocols": {
    "authoringAdapter": 1,
    "devHost": 1,
    "verifier": 1
  },
  "schemas": {
    "scaffold": 2,
    "manifest": 2,
    "generatedArtifacts": 1
  },
  "registry": {
    "kind": "public-npm",
    "portable": true
  },
  "packageManager": "pnpm@10.4.1",
  "releaseSetId": "sha256:dc7f07f20849e6a11b594685c0544a6f02d9bf9cd41a34a27bbabc2989e64eaa"
} as const satisfies AuthoringReleaseSetV1;
