// Generated by scripts/generate-authoring-release-set.ts. Do not edit by hand.
import type { AuthoringReleaseSetV1 } from "./authoring-release-set.js";

export const AUTHORING_RELEASE_SET = {
  "schemaVersion": 1,
  "channel": "public",
  "packages": {
    "cli": {
      "name": "@dreamboard-games/cli",
      "version": "0.1.30-alpha.12"
    },
    "sdk": {
      "name": "@dreamboard-games/sdk",
      "version": "0.4.0-alpha.1"
    },
    "apiClient": {
      "name": "@dreamboard-games/api-client",
      "version": "0.3.0-alpha.3"
    },
    "devHost": {
      "name": "@dreamboard-games/dev-host",
      "version": "0.1.30-alpha.12"
    }
  },
  "protocols": {
    "authoringAdapter": 1,
    "devHost": 1,
    "verifier": 1
  },
  "schemas": {
    "scaffold": 2,
    "manifest": 2,
    "generatedArtifacts": 1
  },
  "registry": {
    "kind": "public-npm",
    "portable": true
  },
  "packageManager": "pnpm@10.4.1",
  "releaseSetId": "sha256:ed64b559e23b9d19f22b1dfd2a8540c1fbb8fea320a9af96795c4fd784d5935a"
} as const satisfies AuthoringReleaseSetV1;
