import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type DocMapping = {
  source: string;
  target: string;
};

const mappings: DocMapping[] = [
  {
    source: "docs/reference/cli.mdx",
    target: "skills/dreamboard/references/cli.md",
  },
  {
    source: "docs/quickstart.mdx",
    target: "skills/dreamboard/references/quickstart.md",
  },
  {
    source: "docs/reference/testing.mdx",
    target: "skills/dreamboard/references/testing.md",
  },
  {
    source: "docs/tutorials/building-your-first-game.mdx",
    target: "skills/dreamboard/references/building-your-first-game.md",
  },
];

function repoRoot(): string {
  return path.resolve(import.meta.dirname, "../../..");
}

function parseFrontmatter(source: string): {
  title: string;
  description: string;
  body: string;
} {
  const match = source.match(/^---\n([\s\S]*?)\n---\n\n?/);
  if (!match) {
    return {
      title: "Untitled",
      description: "",
      body: source,
    };
  }

  const frontmatter = match[1] ?? "";
  return {
    title:
      frontmatter.match(/^title:\s*"?(.+?)"?\s*$/m)?.[1] ?? "Untitled",
    description:
      frontmatter.match(/^description:\s*"?(.+?)"?\s*$/m)?.[1] ?? "",
    body: source.slice(match[0].length),
  };
}

function rewriteLinks(markdown: string): string {
  return markdown
    .replace(/\]\(\/docs\/reference\/([^)]+)\)/g, "](./$1.md)")
    .replace(/\]\(\/docs\/tutorials\/([^)]+)\)/g, "](./$1.md)")
    .replace(/\]\(\.\.\/reference\/([^)]+)\)/g, "](./$1.md)")
    .replace(/\]\(\.\.\/tutorials\/([^)]+)\)/g, "](./$1.md)")
    .replace(/\.mdx\)/g, ".md)");
}

function renderSkillReference(mapping: DocMapping, source: string): string {
  const parsed = parseFrontmatter(source);
  return [
    "<!-- Generated by apps/dreamboard-cli/scripts/sync-skill-docs.ts. -->",
    `<!-- Source: ${mapping.source} -->`,
    "",
    `# ${parsed.title}`,
    "",
    parsed.description,
    "",
    rewriteLinks(parsed.body).trimEnd(),
    "",
  ].join("\n");
}

const root = repoRoot();
for (const mapping of mappings) {
  const sourcePath = path.join(root, mapping.source);
  const targetPath = path.join(root, mapping.target);
  const source = readFileSync(sourcePath, "utf8");
  mkdirSync(path.dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, renderSkillReference(mapping, source));
}
