import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type DocMapping = {
  source: string;
  target: string;
};

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const repoRoot = path.resolve(packageRoot, "..", "..");

const mappings: DocMapping[] = [
  {
    source: "docs/quickstart.mdx",
    target: "skills/dreamboard/references/quickstart.md",
  },
  {
    source: "docs/tutorials/building-your-first-game.mdx",
    target: "skills/dreamboard/references/building-your-first-game.md",
  },
  {
    source: "docs/reference/cli.mdx",
    target: "skills/dreamboard/references/cli.md",
  },
  {
    source: "docs/reference/rule-authoring.mdx",
    target: "skills/dreamboard/references/rule-authoring.md",
  },
  {
    source: "docs/reference/manifest-authoring.mdx",
    target: "skills/dreamboard/references/manifest-authoring.md",
  },
  {
    source: "docs/reference/reducer.mdx",
    target: "skills/dreamboard/references/reducer.md",
  },
  {
    source: "docs/reference/game-interface.mdx",
    target: "skills/dreamboard/references/game-interface.md",
  },
  {
    source: "docs/reference/testing.mdx",
    target: "skills/dreamboard/references/testing.md",
  },
  {
    source: "docs/reference/canonical-concepts.mdx",
    target: "skills/dreamboard/references/canonical-concepts.md",
  },
];

function parseFrontmatter(source: string): {
  body: string;
  title: string | null;
  description: string | null;
} {
  const match = source.match(/^---\n([\s\S]*?)\n---\n\n?/);
  if (!match) {
    return { body: source, title: null, description: null };
  }
  const frontmatter = match[1] ?? "";
  const readString = (key: string) =>
    frontmatter.match(new RegExp(`^${key}:\\s*"?([^"\\n]+)"?\\s*$`, "m"))
      ?.[1]
      ?.trim() ?? null;

  return {
    body: source.slice(match[0].length),
    title: readString("title"),
    description: readString("description"),
  };
}

function rewriteLinks(markdown: string): string {
  return markdown
    .replace(/\]\(\/docs\/reference\/([^)]+)\)/g, "](./$1.md)")
    .replace(/\]\(\/docs\/tutorials\/([^)]+)\)/g, "](./$1.md)")
    .replace(/\]\(\/docs\/quickstart\)/g, "](./quickstart.md)")
    .replace(/\]\(\.\.\/reference\/([^)]+)\)/g, "](./$1.md)")
    .replace(/\]\(\.\.\/tutorials\/([^)]+)\)/g, "](./$1.md)")
    .replaceAll(/<Note>\n([\s\S]*?)\n<\/Note>/g, "$1")
    .replaceAll(/<Warning>\n([\s\S]*?)\n<\/Warning>/g, "$1")
    .replace(/\.mdx\)/g, ".md)");
}

function renderSkillReference(mapping: DocMapping, source: string): string {
  const parsed = parseFrontmatter(source);
  const heading =
    parsed.title && !parsed.body.trimStart().startsWith("# ")
      ? `# ${parsed.title}\n\n`
      : "";
  const summary = parsed.description ? `${parsed.description}\n\n` : "";
  return [
    "<!-- Generated by apps/dreamboard-cli/scripts/sync-skill-docs.ts. -->",
    `<!-- Source: ${mapping.source} -->`,
    "",
    `${heading}${summary}${rewriteLinks(parsed.body)}`.trimEnd(),
    "",
  ].join("\n");
}

for (const mapping of mappings) {
  const sourcePath = path.join(repoRoot, mapping.source);
  const targetPath = path.join(repoRoot, mapping.target);
  const source = await readFile(sourcePath, "utf8");
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, renderSkillReference(mapping, source));
}
