export const REDUCER_TESTING_TYPES_WRAPPER_CONTENT = `\
// Generated by dreamboard — do not edit by hand.
import game from "../app/game";
import { createScenarioAuthoring } from "@dreamboard-games/sdk/testing";

export const { defineScenario } = createScenarioAuthoring(game);
`;
